
pepTalkLine = {
    'Go for it!' 
    'Put a little strut in it!' 
    'Go get it!' 
    'Conquer today!' 
    'Push on!' 
    'Put your game face on!' 
    'You can do it and you know it!'
    'Flex your can do muscle!'
    'Hi-five yourself! (that`s like...a clap :/)'
    'Get through it!'
    'Don`t try harder. Do harder!'
    'Inspire envy.'
    'Be unstoppable!'
    'Don`t give up on yourself!'
    'The show must go on. Or work.'
    'Seize the day!'
    'Nothing you can`t handle!'
    'You`ve survived tougher.'
    'It`s yours for the taking.'
    'Be resilient'
    'Get back in the game'
    'Buckle down and push forth'
    'Let`s hear your battle cry.'
    'Power through!'
    'Take charge and mean it!'
    'Impress yourself today'
    'Bet on yourself'
    'March forward!'
               };
 pepTalkLineNum = roundoff(size(pepTalkLine,1)*rand(),0);
 display(pepTalkLine(pepTalkLineNum));
